# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sales-order-system-terraform-state-s3-bucket"
    dynamodb_table = "sales-order-system-S3-state-lock"
    key            = "app-network/terraform.tfstate"
    region         = "eu-west-2"
  }
}
